# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
react_native_path = '../node_modules/react-native'

target 'syloUI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for syloUI
  pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'cxxreact',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTCameraRoll',
    'RCTWebSocket', # needed for debugging
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  # pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'

  target 'syloUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'syloUI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for syloUI-tvOS
  target 'syloUI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end
end
